version: 0.2
phases:
  install:
    commands:
      - cd $HOME/.goenv && git pull --ff-only && cd -
      - goenv install 1.18.0
      - goenv local 1.18.0
      - go install go.k6.io/xk6/cmd/xk6@latest

  build:
    commands:
      - xk6 build --with github.com/grafana/xk6-exec@latest --with github.com/avitalique/xk6-file@latest
      - ./k6 run tests/simple.js
