version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.16
    commands:
      - go install go.k6.io/xk6/cmd/xk6@v0.4.5
      - xk6 build --with github.com/grafana/xk6-exec@latest --with github.com/avitalique/xk6-file@latest

  build:
    commands:
      - ./k6 run tests/simple.js
