name: Run custom k6 build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  run-script:
    runs-on: ubuntu-latest
    shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - uses: actions/checkout@v2
      - name: install go
        run: |
          sudo sh build-k6.sh
      - name: save env variables
        run: |
          export PATH=/usr/local/go/bin
          sudo $HOME/.profile
          go version
          go install go.k6.io/xk6/cmd/xk6@latest
          export GOPATH=/usr/local/go
          export GOBIN=$GOPATH/bin
          export PATH=$GOPATH/bin:$PATH
          sudo $HOME/.profile
          echo $GOPATH
      - name: build k6
        run: |
          cd /usr/local/go/bin
          pwd
          xk6 build latest \ --with github.com/grafana/xk6-exec@latest \ --with github.com/avitalique/xk6-file@latest
          ./k6 run tests/simple.js
