name: Run custom k6 build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  run-script:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - uses: actions/checkout@v2
      - name: install go
        run: |
          sudo apt-get install git
          sudo wget https://go.dev/dl/go1.18.2.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.2.linux-amd64.tar.gz
      - name: install xk6 and add go to $PATH
        run: |
          go version
          go install go.k6.io/xk6/cmd/xk6@latest
          export GOPATH=/usr/local/go
          export PATH=$PATH:$GOPATH/bin
          source ~/.bashrc
          echo $GOPATH
          echo $PATH
      - name: build k6
        run: |
          cd /usr/local/go/bin
          xk6 build latest \
            --with github.com/grafana/xk6-exec@latest \
            --with github.com/avitalique/xk6-file@latest
          ./k6 run tests/simple.js
