name: Run custom k6 build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  run-script:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - uses: actions/checkout@v2
      - name: install xk6
        run: |
          wget https://github.com/grafana/xk6/releases/download/v0.7.0/xk6_0.7.0_linux_amd64.tar.gz
          ls
          tar -xvf xk6_0.7.0_linux_amd64.tar.gz
      - name: build k6
        run: |
          ./xk6 build latest \
            --with github.com/grafana/xk6-exec@latest \
            --with github.com/avitalique/xk6-file@latest
          ./k6 run tests/simple.js
