name: Run custom k6 build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6
        run: xk6 build \
          --with github.com/grafana/xk6-exec@latest \
          --with github.com/avitalique/xk6-file@latest

      - name: Run load tests
        run: ./k6 run tests/simple.js
