name: Run custom k6 build

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  run-script:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      - uses: actions/checkout@v2
      - name: Start the test
        run: |
          sh build-k6.sh
